export const SET_ROOMS = "SET_ROOMS";
export const GET_ROOM = "GET_ROOM";
export const FILTER_ROOMS_TYPE = "FILTER_ROOMS_TYPE";
export const FILTER_ROOMS_CAPACITY = "FILTER_ROOMS_CAPACITY";
export const FILTER_ROOMS_PRICE = "FILTER_ROOMS_PRICE";
export const FILTER_ROOMS_BREAKFAST = "FILTER_ROOMS_BREAKFAST";
export const FILTER_ROOMS_PETS = "FILTER_ROOMS_PETS";
